services:
    react-app:
        image: paweltylczak/demo-ui:dev-1.0.0
        container_name: demo-container
        ports:
            - "3001:3000"
        environment:
            - NODE_ENV=production
        restart: unless-stopped
