services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: paweltylczak/demo-ui:..11.0.1
    container_name: demo-container
    ports:
      - "3000:3001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
