services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: paweltylczak/demo-ui:1.0.0
    container_name: demo-container
    ports:
      - "3000:3001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
