name: Build Project

on:
  push:
    branches:
      - master

  workflow_dispatch:
    inputs:
      upgradeType:
        description: 'Select upgrade type'
        required: true
        type: choice
        default: PATCH
        options:
          - PATCH
          - MINOR
          - MAJOR

jobs:
  build:
    runs-on: ubuntu-latest

    # The 'environment' is used in the context of GitHub environments, eg. to source secrets/variables
    environment:
      name: build_env
      url: https://dev-app.szkolneplatnosci.pl

    env:
      MANIFEST_REPO_NAME: p-tylczak/release_manifest
      MANIFEST_FILE: ./apps/demo_cicd/dev/demo_cicd.manifest
      DOCKER_COMPOSE_FILE: ./apps/demo_cicd/dev/docker-compose.yaml
      DOCKER_IMAGE_NAME: paweltylczak/demo-ui
      PREV_VERSION_VALUE: do-not-update-manually
      NEXT_VERSION_VALUE: do-not-update-manually
      NODE_VERSION: 22.14.0

    defaults:
      run:
        working-directory: ./app_repo

#    strategy:
#      matrix:
#        environments: [DEV, PROD]

    steps:
      - name: Checkout repo ${{ github.repository }}
        uses: actions/checkout@v4
        with:
          path: app_repo

      - name: Checkout repo ${{ env.MANIFEST_REPO_NAME }}
        uses: actions/checkout@v4
        with:
          repository: ${{ env.MANIFEST_REPO_NAME }}
          token: ${{ secrets.GH_PAT }}
          path: release_manifest

      - name: Configure git
        run: |
          git config --global user.email "github@actions.com"
          git config --global user.name "pipeline runner"

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Run the tests
        run: npm run test

      - name: Build code
        run: npm run build

      - name: Load versions from manifest
        working-directory: ./release_manifest
        run: |
          source ./scripts/setup_version.sh ${{ env.MANIFEST_FILE }} ${{ inputs.upgradeType || 'PATCH' }}
          echo "PREV_VERSION_VALUE=$PREV_VERSION" >> $GITHUB_ENV
          echo "NEXT_VERSION_VALUE=$NEXT_VERSION" >> $GITHUB_ENV

      - name: Echo the next version
        run: echo ${{ env.NEXT_VERSION_VALUE }}

      - name: Build & push image in ALL ENVIRONMENTS
        run: |
          export DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}
          export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}

          echo ========================= DEV =========================
          ${{ secrets.ENV_VARS_DEV }} > .env.dev
          cat .env.dev
          source .env.dev
          echo $BUILD_ENVIRONMENT
          ./scripts/docker-build-image.sh dev ${{ env.NEXT_VERSION_VALUE }}

          echo ========================= PROD =========================
          ${{ secrets.ENV_VARS_PROD }} > .env.prod
          cat .env.prod
          source .env.prod
          echo $BUILD_ENVIRONMENT
          ./scripts/docker-build-image.sh prod ${{ env.NEXT_VERSION_VALUE }}

      - name: Append new version to manifest
        working-directory: ./release_manifest
        run: |
          echo "export VERSION=$NEXT_VERSION_VALUE" >> ${{ env.MANIFEST_FILE }}
          git commit -am "[bot] append version ${{ env.NEXT_VERSION_VALUE }}"
          git push

      - name: Amend docker compose version
        working-directory: ./release_manifest
        run: |
          sed -i 's?${{ env.DOCKER_IMAGE_NAME }}:dev-${{ env.PREV_VERSION_VALUE }}?${{ env.DOCKER_IMAGE_NAME}}:dev-${{ env.NEXT_VERSION_VALUE }}?g' ${{ env.DOCKER_COMPOSE_FILE }}
          git commit -am "[bot] bump version from ${{ env.PREV_VERSION_VALUE }} to ${{ env.NEXT_VERSION_VALUE }}"
          git push