name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.15.X]

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run the tests and generate coverage report
        run: npm run test

      - name: Build
        run: npm run build

      - name: "Check tags"
        run: git tag

      - name: Create report file
        run: date +%s > report.txt

      - name: Commit report
        run: |
          git config user.email "github@actions.com"
          git config user.name "pipeline runner"
          git commit add .
          git commit -m "Automated report"
          git push