name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      MANIFEST_REPO_NAME: p-tylczak/release_manifest
      MANIFEST_FILE: demo_cicd.manifest

    defaults:
      run:
        working-directory: ./app_repo

    strategy:
      matrix:
        node-version: [20.15.X]

    steps:
      - name: Configure git
        run: |
          git config --global user.email "github@actions.com"
          git config --global user.name "pipeline runner"

      - name: Checkout repo ${{ github.repository }}
        uses: actions/checkout@v4
        with:
          path: app_repo

      - name: Checkout repo ${{ env.MANIFEST_REPO_NAME }}
        uses: actions/checkout@v4
        with:
          repository: ${{ env.MANIFEST_REPO_NAME }}
          token: ${{ secrets.GH_PAT }}
          path: release_manifest

      - name: Load versions from manifest
        working-directory: ./release_manifest
        run: source ./scripts/setup_version.sh ${{env.MANIFEST_FILE}} PATCH

      - name: Append new version to manifest
        working-directory: ./release_manifest
        run: |
          echo export VERSION=$NEXT_VERSION >> ${{ env.MANIFEST_FILE }}
          git commit -am "[bot] append version"
          git push

      - name: Confirm the next version
        run: echo $NEXT_VERSION

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run the tests and generate coverage report
        run: npm run test

      - name: Build
        run: npm run build

      - name: Commit report
        run: |
          git add .
          git commit -m "Automated report"
          git push